### ISSUE TITLE
Error on load blazor wasm em .net 9 with serviceworker

### ISSUE THREAD

**Issue by rftd** [LostBeard/SpawnDev.BlazorJS.WebWorkers#3]
![image](https://github.com/user-attachments/assets/e8893dfd-a5a7-4da0-b456-00ac9cafea12)

```
Uncaught (in promise) Error: Failed to start platform. Reason: Error: Failed to load config file ./blazor.boot.json SyntaxError: Cannot use import statement outside a module SyntaxError: Cannot use import statement outside a module
    at new Function (<anonymous>)
    at https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18
    at async eval (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:38732)
    at async Promise.all (index 1)
    at async lt.importInitializersAsync (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:38587)
    at async eval (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:41731)
    at async Object.onConfigLoaded (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:41415)
    at async Le (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:24239)
    at async eval (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:33722)
    at async eval (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:39985)
    at new Function (<anonymous>)
    at https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18
    at async eval (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:38732)
    at async Promise.all (index 1)
    at async lt.importInitializersAsync (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:38587)
    at async eval (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:41731)
    at async Object.onConfigLoaded (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:41415)
    at async Le (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:24239)
    at async eval (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:33722)
    at async eval (eval at <anonymous> (https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1:313:18), <anonymous>:5:39985)
    at qt (eval at initScriptElement (https://localhost:7116/spawndev.blazorjs.webworkers.faux-env.js:280:26), <anonymous>:3:55661)
```

**Comment by LostBeard** [comment]
Hello. Thanks for reporting your issue. Let's see if we can figure this out.  

What browser are you using?  
What version of `SpawnDev.BlazorJS.WebWorkers`?  
Any chance you can share the project on GitHub? It is fine if not, it just makes it easier for me to reproduce the issue.

**Comment by LostBeard** [comment]
Can you share your `index.html`? (if not already sharing the project...)

It looks like the issue is possibly being caused by a by a `<script>`  tag in your `index.html` that is being loaded in the worker.

**Comment by rftd** [comment]
What browser are you using?
Microsoft Edge

What version of SpawnDev.BlazorJS.WebWorkers?
2.5.22

[index.zip](https://github.com/user-attachments/files/17912234/index.zip)

**Comment by rftd** [comment]
I will make a sample app to share tomorrow.

**Comment by LostBeard** [comment]
I see `https://localhost:7116/spawndev.blazorjs.webworkers.js?importServiceWorkerAssets=1` in your error.

Looks like you are using something similar to the below in your `Program.cs` to run your app up in the ServiceWorker as described here [BlazorServiceWorkerDemo](https://github.com/LostBeard/BlazorServiceWorkerDemo). 

```cs
builder.Services.RegisterServiceWorker<PWAServiceWorker>(new ServiceWorkerConfig
{
    ImportServiceWorkerAssets = true,
});
```

And it is the service worker starting up that appears to be throwing the error. Not sure where exactly the issue lies, but I'll be able to narrow it down with your sample app. 👍

**Comment by LostBeard** [comment]
I am assuming you got this issue resolved. If not, feel free to re-open and add more details and I will gladly assist.

**Comment by rftd** [comment]
Sorry for not getting back to you, it was busy here.
I couldn't fix it, but when I was doing the demo I also couldn't reproduce the same error and as it was a new project I decided to restart since I hadn't done much.
For now everything is working as expected, thank you very much for your help.

**Comment by LostBeard** [comment]
Not a problem! Thank you for posting your issue, and please post any future issues. I enjoy diagnosing and solving problems. 

I'm here to help if you need it. 👍
